tasks:
  - name: terraform
    before: |
      sudo apt-get update && sudo apt-get install -y gnupg software-properties-common uuid tree
      wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
      gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt-get update && sudo apt-get install terraform
      source ./bin/tflogin.sh
      source ./bin/tfalias.sh
      cp $PROJECT_ROOT/examples/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      /usr/local/bin/aws sts get-caller-identity
      sudo rm awscliv2.zip
      sudo rm -rf aws
      cd $PROJECT_ROOT
  - name: http-server
    before: |
      npm install -g http-server
    command: 
      http-server -p 8080

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform